#farthest a player can teleport to another player with /police tp
#setting this value to 0 makes the command like a normal teleport.
MaxPoliceTp: 50
#should we pay the police officer for arresting a player?
PayPoliceOnArrest: true
#if we are going to pay the police officer, how much should we pay them?
MoneyToGiveToPoliceOnArrest: 500
#should we make the player loose money on an arrest (note: this money will not go to the police, it will be trashed)
TakeMoneyOnArrest: false
#if the setting above is true, what percent of the money should be taken. Put values like 20 for 20% do not put a %.
PercentOfMoneyToTake: 20
#if you have worldguard installed and want to enable "safe areas" or areas where police can't arrest players
SafeArea: false
#if the above value is true, then the regions that you want listed as "safe areas" due note that at the moment, you can't use the __global__ region
#Make sure to use lower case!
SafeAreas:
 - examplesafearea1
 - examplesafearea2
 #material to use for the arresting baton (make sure the material is in caps) ex: BLAZE_ROD
BatonMaterialType: BLAZE_ROD
#enable frisking or not
Frisking: true
#if frisking is enabled, what percent should their be per inventory slot of finding controband (ex plugin finds controband but because its set to 20% for findind, then theres a 20% chance that, that item will be flagged by the police
PercentOfFindingContraband: 20
#material to use for the frisking stick (make sure the material is in caps) ex: BLAZE_ROD
FriskStickMaterialType: BLAZE_ROD
#mark all guns as contraband items. Note: this requries quality armory and frisking to be enabled
MarkAllGunsAsContraband: false
#should /911 show players cords?
ShowCords911: false
#frisk cooldown in seconds
FriskCooldown: 600
CmdFor911: 911
CmdForPolice: police
ArrestGUI:
 - Item1:
    - Material: AIR
    - JailTime:
    - Perm:
 - Item2:
     - Material: AIR
     - JailTime:
     - Perm:
 - Item3:
     - Material: RED_TERRACOTTA
     - JailTime: 4.0
     - Perm:
 - Item4:
     - Material: ORANGE_TERRACOTTA
     - JailTime: 8.0
     - Perm:
 - Item5:
     - Material: YELLOW_TERRACOTTA
     - JailTime: 10.0
     - Perm:
 - Item6:
     - Material: LIME_TERRACOTTA
     - JailTime: 12.0
     - Perm:
 - Item7:
     - Material: LIGHT_BLUE_TERRACOTTA
     - JailTime: 15.0
     - Perm:
 - Item8:
     - Material: Air
     - JailTime:
     - Perm:
 - Item9:
     - Material: Air
     - JailTime:
     - Perm: