name: SimplePolice
api-version: 1.13
author: ramdon_person
main: com.voidcitymc.plugins.SimplePolice.SPPlugin
version: 3.4
depend: [Essentials]
softdepend: [Vault, QualityArmory, WorldGuard, WorldEdit]
website: https://plugins.voidcitymc.com
commands:
  police:
    description: The main command of Simple Police
    usage: /police
  911:
    description: Call the cops!
    usage: /911
permissions:
  police.add:
    description: Allows you to add a police
    default: op
  police.remove:
    description: Allows you to remove a police
    default: op
  police.help:
    description: Allows you to see the help pages
    default: op
  police.list:
    description: Allows you to see the list of police
    default: op
  police.unjail:
    description: Allows you to unjail someone
    default: op
  police.admin:
    description: Allows you to reload the config, add items to frisk list etc.
    default: op
  police.tp:
    description: Allows you to police tp to a player
    default: op
