name: SimplePolice
author: ramdon_person
main: com.voidcitymc.plugins.SimplePolice
version: 2.0
api-version: 1.15
depend: [Essentials]
website: https://plugins.voidcitymc.com
commands:
   police:
      description: Your description
      usage: /police

permissions:
  police.add:
    description: Allows you to add a police
    default: false
  police.remove:
    description: Allows you to remove a police
    default: false
  police.help:
    description: Allows you to see the help pages
    default: false
  police.list:
    description: Allows you to see the list of police
    default: false
  police.unjail:
    description: Allows you to unjail someone
    default: false
  police.reload:
    description: Allows you to reload the config
    default: false
  police.tp:
    description: Allows you to police tp to a player
    default: false
