name: SimplePolice
api-version: 1.13
author: ramdon_person
main: com.voidcitymc.plugins.SimplePolice.Main
version: 3.0
depend: [Essentials]
softdepend: [Vault, WorldGuard, WorldEdit]
website: https://plugins.voidcitymc.com
commands:
   police:
      description: Your description
      usage: /police
   911:
      description: Call the cops!
      usage: /911

permissions:
  police.add:
    description: Allows you to add a police
    default: op
  police.remove:
    description: Allows you to remove a police
    default: op
  police.help:
    description: Allows you to see the help pages
    default: op
  police.list:
    description: Allows you to see the list of police
    default: op
  police.unjail:
    description: Allows you to unjail someone
    default: op
  police.reload:
    description: Allows you to reload the config
    default: op
  police.tp:
    description: Allows you to police tp to a player
    default: op
